server:
  port: 8090

spring:
  application:
    name: consultacep

resilience4j:
  retry:
    instances:
      cepApi:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
