server:
  port: 8090

spring:
  application:
    name: consultacep

resilience4j:
  retry:
    instances:
      cepApi:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - java.lang.IllegalArgumentException

  circuitbreaker:
    instances:
      cepApi:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - java.lang.IllegalArgumentException

  timelimiter:
    instances:
      cepApi:
        timeoutDuration: 2s
